# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='prev_state',
            field=models.BooleanField(default=False),
        ),
    ]
