# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='ads', max_length=64),
            preserve_default=False,
        ),
    ]
