# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='created', max_length=64),
            preserve_default=False,
        ),
    ]
